name:
  mariadb
services:
  mariadb:
    image:
      mariadb:latest
    container_name:
      mariadb
    networks:
      default:
        null
    ports:
      - mode: ingress
        target: 3306
        published: "3306"
        protocol: tcp
    restart:
      unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD:
        ${MARIADB_ROOT_PASSWORD}
    volumes:
      - type: volume
        source: data
        target: /var/lib/mysql
    command:
        ${MARIADB_EXTRA_FLAGS}
volumes:
  data:
