name:
  watcher
services:
  watcher:
    image:
      python:3.11-alpine
    container_name:
      watcher
    volumes:
      - /home/ubuntu/images:/images
      - /home/ubuntu/images/watcher/watcher.py:/watcher.py
    command:
      sh -c "pip install watchdog -q && python3 /watcher.py"
    restart:
      unless-stopped
